<?xml version="1.0" encoding="utf-8"?><Database Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="lesson">
    <Type Name="lesson">
      <Column Member="Id" AutoSync="Never" Type="int " IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Member="content" Type="System.String" CanBeNull="false" />
      <Column Member="time" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
</Database>